### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by cat-dog-fight** [jfeng45/servicetmpl#1]
发现 切换到 CouchDB, 总会插入一个  "function(doc) {\n  if (doc.uid) {\n emit(doc.uid, doc);\n}\n}" 的 views, 这里 couchDb 是 起什么作用的呢

**Comment by jfeng45** [comment]
我在程序里用了MYSQL和CouchDB做数据库是想说明这种架构可以同时支持不同的数据库（而且数据库的类型也可以不一致，例如SQL和NoSQL），而且在转换数据库时不需要更改程序。
至于CouchDB的view，当你要在CouchDB里做查询时先要建立view，但大多数人可能并不熟悉CouchDB，不知道如何建立view。为了方便他们，我把view写在程序里了，这样执行Find(id int)时就自动把view建立了，不需要额外的动作。当然这只是权宜之计，不能放在真正的程序里。在生产环境里还是要单独建view的。
